"""Tests for invoice field extraction and the upload endpoint.

Most of these drive `extract_fields` with plain text — it is pure, so a PDF is
only needed for the tests that are actually about PDF reading. The fixtures are
generated by tests/fixtures/make_invoice_pdfs.py and committed alongside it.
"""

import inspect
import re
import tempfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from src.customsiq import api, auth, document_extraction
from src.customsiq.api import app
from src.customsiq.config import settings
from src.customsiq.document_extraction import (
    FIELD_LABELS,
    extract_fields,
    extract_invoice,
    extract_text,
)
from src.customsiq.exceptions import InvalidQueryError
from tests.helpers import PASSWORD, create_test_user, signed_in_client

FIXTURES = Path(__file__).parent / "fixtures"
SAMPLE_PDF = FIXTURES / "sample_invoice.pdf"
SCANNED_PDF = FIXTURES / "scanned_invoice.pdf"
PDF_HEADERS = {"Content-Type": "application/pdf"}

client = TestClient(app)

# The worked example from the plan and the README.
FULL_INVOICE = """COMMERCIAL INVOICE                         Invoice No: INV-2026-0417
                                           Date: 2026-03-14

Exporter:  Solvia Textiles AS, Oslo
Consignee: Northwind Maritime Holdings Ltd, Limassol

Description of Goods: Cotton T-shirts, knitted
HS Code:              6109100000
Country of Origin:    Norway
Invoice Value:        EUR 12,450.00
"""

# Half the fields absent — the expected case, not an error.
PARTIAL_INVOICE = """COMMERCIAL INVOICE

Description: Portable computers, laptops
Total Amount: USD 3400.00

Delivery: DAP Rotterdam
"""

# Same data, different vocabulary, to prove the synonym lists earn their keep.
ALTERNATIVE_LABELS = """Commodity Code - 8471300000
Made In - DE
Total Invoice Value - 1.234,56 EUR
Supplier - Aurora Precision Components GmbH
Goods Description - Portable computers
"""


def values(result) -> dict:
    """Field name -> value, for terse assertions."""
    return {field.name: field.value for field in result.fields}


class TestFieldDetection:
    """Labelled lines in, structured fields out."""

    def test_reads_every_field_from_a_fully_labelled_invoice(self) -> None:
        result = extract_fields(FULL_INVOICE)
        assert values(result) == {
            "description": "Cotton T-shirts, knitted",
            "hs_code": "6109100000",
            "country_of_origin": "NO",
            "customs_value": "12450.0",
            "currency": "EUR",
            "party_name": "Northwind Maritime Holdings Ltd, Limassol",
        }
        assert result.missing == []
        assert result.completeness == 1.0

    def test_reports_missing_fields_instead_of_guessing(self) -> None:
        """A partial invoice is normal; the result says what it couldn't find."""
        result = extract_fields(PARTIAL_INVOICE)
        assert values(result) == {
            "description": "Portable computers, laptops",
            "customs_value": "3400.0",
            "currency": "USD",
        }
        assert set(result.missing) == {"hs_code", "country_of_origin", "party_name"}
        assert result.completeness == 0.5
        assert result.value_of("hs_code") is None

    def test_synonym_labels_are_recognised(self) -> None:
        result = extract_fields(ALTERNATIVE_LABELS)
        assert values(result) == {
            "hs_code": "8471300000",
            "country_of_origin": "DE",
            "customs_value": "1234.56",
            "currency": "EUR",
            "party_name": "Aurora Precision Components GmbH",
            "description": "Portable computers",
        }

    def test_every_field_reports_the_label_and_line_it_came_from(self) -> None:
        """Explainability, the same contract as matched_terms and risk factors."""
        origin = next(
            f for f in extract_fields(FULL_INVOICE).fields if f.name == "country_of_origin"
        )
        assert origin.label == "Country of Origin"
        assert origin.source_line.strip() == "Country of Origin:    Norway"
        assert origin.value == "NO"  # normalized, while the line stays verbatim

    def test_the_longest_matching_label_on_a_line_wins(self) -> None:
        """ "Commodity Code" must not be read as description's "Commodity"."""
        result = extract_fields("Commodity Code: 6109100000")
        assert values(result) == {"hs_code": "6109100000"}

    def test_consignee_beats_exporter_regardless_of_page_order(self) -> None:
        """Screening is about the counterparty, and Exporter comes first here."""
        party = next(f for f in extract_fields(FULL_INVOICE).fields if f.name == "party_name")
        assert party.label == "Consignee"

    def test_unlabelled_text_yields_nothing_rather_than_noise(self) -> None:
        result = extract_fields("Thank you for your business.\nPlease remit within 30 days.")
        assert result.fields == []
        assert len(result.missing) == len(FIELD_LABELS) + 1

    def test_a_blank_value_after_a_label_is_not_a_field(self) -> None:
        assert extract_fields("Country of Origin:   ").fields == []


class TestNormalization:
    """Values are normalized only where this project already defines 'valid'."""

    @pytest.mark.parametrize(
        ("line", "expected"),
        [
            ("Country of Origin: Norway", "NO"),
            ("Country of Origin: NO", "NO"),
            ("Country of Origin: norway", "NO"),
            ("Made In: Germany", "DE"),
        ],
    )
    def test_country_names_and_codes_both_resolve(self, line: str, expected: str) -> None:
        assert extract_fields(line).value_of("country_of_origin") == expected

    def test_an_unknown_country_stays_raw_and_is_noted(self) -> None:
        """Honest: it's surfaced for the user to fix, not silently dropped."""
        result = extract_fields("Country of Origin: Atlantis")
        assert result.value_of("country_of_origin") == "Atlantis"
        assert any("Atlantis" in note for note in result.notes)

    @pytest.mark.parametrize(
        ("raw", "expected"),
        [
            ("EUR 12,450.00", "12450.0"),
            ("1.234,56", "1234.56"),
            ("3400.00", "3400.0"),
            ("3.400", "3400.0"),
            ("USD 3400", "3400.0"),
            ("950,50", "950.5"),
        ],
    )
    def test_both_separator_conventions_parse(self, raw: str, expected: str) -> None:
        assert extract_fields(f"Invoice Value: {raw}").value_of("customs_value") == expected

    @pytest.mark.parametrize(
        ("raw", "expected"),
        [("EUR 100", "EUR"), ("€ 100", "EUR"), ("$100.00", "USD"), ("100 GBP", "GBP")],
    )
    def test_currency_is_read_from_the_value_line(self, raw: str, expected: str) -> None:
        assert extract_fields(f"Invoice Value: {raw}").value_of("currency") == expected

    def test_a_value_with_no_number_is_ignored_and_noted(self) -> None:
        result = extract_fields("Invoice Value: on request")
        assert result.value_of("customs_value") is None
        assert result.notes

    @pytest.mark.parametrize("raw", ["6109 10 0000", "6109.10.0000", "6109100000"])
    def test_grouped_hs_codes_are_normalized_to_digits(self, raw: str) -> None:
        assert extract_fields(f"HS Code: {raw}").value_of("hs_code") == "6109100000"

    @pytest.mark.parametrize("raw", ["6109100", "ABCDEFGH", "61091000001"])
    def test_a_non_cn_code_is_rejected_not_passed_through(self, raw: str) -> None:
        """Reuses validate_cn_code, so 'valid' means what it means everywhere else."""
        result = extract_fields(f"HS Code: {raw}")
        assert result.value_of("hs_code") is None
        assert "hs_code" in result.missing
        assert result.notes


class TestPdfReading:
    """The pypdf path: real files, including the ones that can't be read."""

    def test_extracts_text_from_a_real_pdf(self) -> None:
        text, pages = extract_text(SAMPLE_PDF.read_bytes())
        assert pages == 1
        assert "Country of Origin:" in text

    def test_end_to_end_from_pdf_bytes_to_fields(self) -> None:
        result = extract_invoice(SAMPLE_PDF.read_bytes())
        assert result.value_of("hs_code") == "6109100000"
        assert result.value_of("country_of_origin") == "NO"
        assert result.page_count == 1
        assert result.has_text_layer

    def test_a_scanned_pdf_is_reported_as_such(self) -> None:
        """Not an empty result that looks like a parser bug — a stated limit."""
        result = extract_invoice(SCANNED_PDF.read_bytes())
        assert result.has_text_layer is False
        assert result.fields == []
        assert any("no text layer" in note for note in result.notes)
        assert any("recognition isn't available" in note for note in result.notes)

    def test_non_pdf_bytes_are_refused(self) -> None:
        with pytest.raises(InvalidQueryError, match="isn't a PDF"):
            extract_text(b"\x89PNG\r\n\x1a\n" + b"0" * 100)

    def test_a_damaged_pdf_raises_cleanly(self) -> None:
        """A parse failure must be a 400-shaped error, never a traceback."""
        with pytest.raises(InvalidQueryError):
            extract_text(b"%PDF-1.4\nthis is not really a pdf")


class TestUploadEndpoint:
    """POST /extract-invoice — auth, limits, and content-based typing."""

    def test_anonymous_upload_is_refused(self) -> None:
        response = client.post(
            "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
        )
        assert response.status_code == 401

    def test_a_signed_in_viewer_may_upload(self) -> None:
        """Viewer is the floor, so the published demo account can try it."""
        with signed_in_client(auth.VIEWER) as viewer:
            response = viewer.post(
                "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
            )
        assert response.status_code == 200
        body = response.json()
        assert body["completeness"] == 1.0
        assert body["missing"] == []
        assert {f["name"] for f in body["fields"]} == set(FIELD_LABELS) | {"currency"}

    def test_the_response_carries_the_evidence_for_each_field(self) -> None:
        with signed_in_client(auth.VIEWER) as viewer:
            body = viewer.post(
                "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
            ).json()
        hs_code = next(f for f in body["fields"] if f["name"] == "hs_code")
        assert hs_code == {
            "name": "hs_code",
            "value": "6109100000",
            "label": "HS Code",
            "source_line": hs_code["source_line"],
        }
        assert "6109100000" in hs_code["source_line"]

    def test_the_endpoint_does_not_classify_price_or_score(self) -> None:
        """It returns fields for review; the user presses the existing buttons."""
        with signed_in_client(auth.VIEWER) as viewer:
            body = viewer.post(
                "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
            ).json()
        for key in ("level", "composite_score", "factors", "duty_amount", "score"):
            assert key not in body

    def test_content_decides_the_type_not_the_declared_one(self) -> None:
        """PNG bytes sent as application/pdf are still refused."""
        with signed_in_client(auth.VIEWER) as viewer:
            response = viewer.post(
                "/extract-invoice", content=b"\x89PNG\r\n\x1a\n" + b"0" * 200, headers=PDF_HEADERS
            )
        assert response.status_code == 415

    def test_an_oversize_upload_is_refused(self) -> None:
        with signed_in_client(auth.VIEWER) as viewer:
            response = viewer.post(
                "/extract-invoice",
                content=b"%PDF-" + b"x" * (settings.upload_max_bytes + 1),
                headers=PDF_HEADERS,
            )
        assert response.status_code == 413

    def test_a_damaged_pdf_is_a_400(self) -> None:
        with signed_in_client(auth.VIEWER) as viewer:
            response = viewer.post(
                "/extract-invoice", content=b"%PDF-1.4\nbroken", headers=PDF_HEADERS
            )
        assert response.status_code == 400

    def test_uploads_are_rate_limited_per_account(self) -> None:
        with signed_in_client(auth.VIEWER) as viewer:
            codes = [
                viewer.post(
                    "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
                ).status_code
                for _ in range(settings.upload_rate_limit_per_minute + 2)
            ]
        assert codes[0] == 200
        assert codes[-1] == 429

    def test_one_account_hitting_the_limit_does_not_lock_out_another(self) -> None:
        """The counter is keyed per account, not global."""
        with signed_in_client(auth.VIEWER) as heavy:
            for _ in range(settings.upload_rate_limit_per_minute + 1):
                heavy.post("/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS)
            assert (
                heavy.post(
                    "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
                ).status_code
                == 429
            )

        with signed_in_client(auth.VIEWER) as fresh:
            assert (
                fresh.post(
                    "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
                ).status_code
                == 200
            )


class TestRateLimitIsApplicationMemoryOnly:
    """The limiter must not depend on which database backend is configured."""

    def test_the_limiter_touches_no_database(self) -> None:
        """Source-level: no connection, no SQL, so SQLite and Postgres behave alike."""
        source = inspect.getsource(api._check_rate_limit)
        for forbidden in ("_conn", "execute", "SELECT", "INSERT", "database"):
            assert forbidden not in source

    def test_the_limiter_runs_with_no_database_involved(self) -> None:
        """Driven past the threshold directly — nothing here opens a connection."""
        api._UPLOAD_HITS.pop("limiter-probe", None)
        for _ in range(settings.upload_rate_limit_per_minute):
            api._check_rate_limit("limiter-probe")
        with pytest.raises(Exception) as exc_info:
            api._check_rate_limit("limiter-probe")
        assert exc_info.value.status_code == 429  # type: ignore[attr-defined]
        api._UPLOAD_HITS.pop("limiter-probe", None)

    def test_state_lives_in_one_process_level_dict(self) -> None:
        """Not per connection, per session or per backend — one dict, keyed by user."""
        assert isinstance(api._UPLOAD_HITS, dict)
        api._UPLOAD_HITS.pop("probe-a", None)
        api._check_rate_limit("probe-a")
        assert "probe-a" in api._UPLOAD_HITS
        api._UPLOAD_HITS.pop("probe-a", None)


class TestNothingIsPersisted:
    """An upload must leave no trace on disk after the request completes."""

    def test_the_module_never_writes_a_file(self) -> None:
        source = Path(document_extraction.__file__).read_text(encoding="utf-8")
        for forbidden in ("open(", "tempfile", "NamedTemporary", ".write(", "shutil"):
            assert forbidden not in source, f"{forbidden} appears in document_extraction.py"

    def test_no_file_appears_anywhere_after_a_real_upload(self) -> None:
        """Snapshot the working directory and the temp directory around a request."""
        temp_dir = Path(tempfile.gettempdir())
        before_cwd = set(Path.cwd().iterdir())
        before_tmp = set(temp_dir.iterdir())

        with signed_in_client(auth.VIEWER) as viewer:
            assert (
                viewer.post(
                    "/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS
                ).status_code
                == 200
            )

        assert set(Path.cwd().iterdir()) - before_cwd == set()
        assert set(temp_dir.iterdir()) - before_tmp == set()

    def test_the_document_text_is_not_written_to_the_database(self) -> None:
        """No table gains a row: extraction is stateless by construction."""
        counts = lambda: [  # noqa: E731 - terse on purpose, used twice
            api._conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            for table in ("review_decisions", "hs_codes", "cn_code_versions", "users")
        ]
        before = counts()
        user = create_test_user(api._conn, auth.VIEWER)
        with TestClient(app) as viewer:
            viewer.post("/auth/login", json={"username": user.username, "password": PASSWORD})
            viewer.post("/extract-invoice", content=SAMPLE_PDF.read_bytes(), headers=PDF_HEADERS)
        after = counts()
        # Only `users` moved, and only because the test itself made an account.
        assert after[:3] == before[:3]


class TestCompositionBoundary:
    """This module pre-fills the decision modules; it never becomes one."""

    def test_it_imports_none_of_the_seven_decision_modules(self) -> None:
        source = Path(document_extraction.__file__).read_text(encoding="utf-8")
        for module in (
            "search",
            "embargo_screener",
            "tariff_calculator",
            "cn_classifier",
            "review",
            "dashboard",
            "risk",
        ):
            assert f"import {module}" not in source
            assert f"from src.customsiq.{module}" not in source

    def test_every_extracted_field_has_a_translation_in_all_three_languages(self) -> None:
        """The frontend builds these keys dynamically, so the i18n scraper misses them."""
        page = (Path(document_extraction.__file__).parent / "static" / "index.html").read_text(
            encoding="utf-8"
        )
        for name in list(FIELD_LABELS) + ["currency"]:
            assert len(re.findall(rf"\b{name}: \"", page)) >= 3, f"{name} lacks EN/TR/DE labels"
