"""Word lists for the rule-based assistant: country names and Turkish product names.

The catalogue is searchable in English (and the bundled German/French), not in
Turkish, so a Turkish product word is looked up here first and the English term
is what gets classified. These are plain dictionaries, deliberately small and
reviewable: a missing word means the assistant asks for an English name or a
code, never that it guesses.
"""

#: ISO 3166-1 alpha-2 code -> names people type for it (lower case, without
#: Turkish case suffixes: "almanya" also matches "Almanya'dan").
COUNTRY_NAMES: dict[str, tuple[str, ...]] = {
    "TR": ("türkiye", "turkiye", "turkey", "türkei", "turkei"),
    "DE": ("almanya", "germany", "deutschland"),
    "FR": ("fransa", "france", "frankreich"),
    "IT": ("italya", "italy", "italien"),
    "ES": ("ispanya", "spain", "spanien"),
    "PT": ("portekiz", "portugal"),
    "NL": ("hollanda", "netherlands", "holland", "niederlande"),
    "BE": ("belçika", "belcika", "belgium", "belgien"),
    "LU": ("lüksemburg", "luksemburg", "luxembourg", "luxemburg"),
    "AT": ("avusturya", "austria", "österreich", "osterreich"),
    "PL": ("polonya", "poland", "polen"),
    "CZ": ("çekya", "cekya", "çek cumhuriyeti", "czechia", "czech republic", "tschechien"),
    "SK": ("slovakya", "slovakia", "slowakei"),
    "HU": ("macaristan", "hungary", "ungarn"),
    "RO": ("romanya", "romania", "rumänien"),
    "BG": ("bulgaristan", "bulgaria", "bulgarien"),
    "GR": ("yunanistan", "greece", "griechenland"),
    "CY": ("kıbrıs", "kibris", "cyprus", "zypern"),
    "MT": ("malta",),
    "SI": ("slovenya", "slovenia", "slowenien"),
    "HR": ("hırvatistan", "hirvatistan", "croatia", "kroatien"),
    "DK": ("danimarka", "denmark", "dänemark"),
    "SE": ("isveç", "isvec", "sweden", "schweden"),
    "FI": ("finlandiya", "finland", "finnland"),
    "EE": ("estonya", "estonia", "estland"),
    "LV": ("letonya", "latvia", "lettland"),
    "LT": ("litvanya", "lithuania", "litauen"),
    "IE": ("irlanda", "ireland", "irland"),
    "GB": ("ingiltere", "birleşik krallık", "united kingdom", "england", "britain", "uk"),
    "CH": ("isviçre", "isvicre", "switzerland", "schweiz"),
    "NO": ("norveç", "norvec", "norway", "norwegen"),
    "IS": ("izlanda", "iceland", "island"),
    "UA": ("ukrayna", "ukraine"),
    "RU": ("rusya", "russia", "russland"),
    "BY": ("belarus", "beyaz rusya", "weißrussland"),
    "RS": ("sırbistan", "sirbistan", "serbia", "serbien"),
    "AL": ("arnavutluk", "albania", "albanien"),
    "MK": ("kuzey makedonya", "makedonya", "north macedonia", "nordmazedonien"),
    "GE": ("gürcistan", "gurcistan", "georgia", "georgien"),
    "AZ": ("azerbaycan", "azerbaijan", "aserbaidschan"),
    "CN": ("çin", "cin", "china"),
    "JP": ("japonya", "japan"),
    "KR": ("güney kore", "guney kore", "kore", "south korea", "korea", "südkorea"),
    "IN": ("hindistan", "india", "indien"),
    "PK": ("pakistan",),
    "BD": ("bangladeş", "banglades", "bangladesh", "bangladesch"),
    "VN": ("vietnam",),
    "TH": ("tayland", "thailand"),
    "ID": ("endonezya", "indonesia", "indonesien"),
    "MY": ("malezya", "malaysia"),
    "TW": ("tayvan", "taiwan"),
    "IR": ("iran",),
    "IQ": ("irak", "iraq"),
    "SA": ("suudi arabistan", "saudi arabia", "saudi-arabien"),
    "AE": ("birleşik arap emirlikleri", "bae", "dubai", "united arab emirates", "uae"),
    "IL": ("israil", "israel"),
    "EG": ("mısır", "misir", "egypt", "ägypten"),
    "MA": ("fas", "morocco", "marokko"),
    "TN": ("tunus", "tunisia", "tunesien"),
    "ZA": ("güney afrika", "south africa", "südafrika"),
    "US": ("amerika", "abd", "amerika birleşik devletleri", "usa", "united states", "america"),
    "CA": ("kanada", "canada"),
    "MX": ("meksika", "mexico", "mexiko"),
    "BR": ("brezilya", "brazil", "brasilien"),
    "AR": ("arjantin", "argentina", "argentinien"),
    "CL": ("şili", "sili", "chile"),
    "AU": ("avustralya", "australia", "australien"),
    "NZ": ("yeni zelanda", "new zealand", "neuseeland"),
}

#: How a country is written in English and German answers: code -> (en, de).
#: Turkish answers use the first name in COUNTRY_NAMES.
COUNTRY_LABELS: dict[str, tuple[str, str]] = {
    "TR": ("Turkey", "der Türkei"), "DE": ("Germany", "Deutschland"),
    "FR": ("France", "Frankreich"), "IT": ("Italy", "Italien"), "ES": ("Spain", "Spanien"),
    "PT": ("Portugal", "Portugal"), "NL": ("the Netherlands", "den Niederlanden"),
    "BE": ("Belgium", "Belgien"), "LU": ("Luxembourg", "Luxemburg"),
    "AT": ("Austria", "Österreich"), "PL": ("Poland", "Polen"),
    "CZ": ("Czechia", "Tschechien"), "SK": ("Slovakia", "der Slowakei"),
    "HU": ("Hungary", "Ungarn"), "RO": ("Romania", "Rumänien"), "BG": ("Bulgaria", "Bulgarien"),
    "GR": ("Greece", "Griechenland"), "CY": ("Cyprus", "Zypern"), "MT": ("Malta", "Malta"),
    "SI": ("Slovenia", "Slowenien"), "HR": ("Croatia", "Kroatien"),
    "DK": ("Denmark", "Dänemark"), "SE": ("Sweden", "Schweden"), "FI": ("Finland", "Finnland"),
    "EE": ("Estonia", "Estland"), "LV": ("Latvia", "Lettland"), "LT": ("Lithuania", "Litauen"),
    "IE": ("Ireland", "Irland"), "GB": ("the United Kingdom", "dem Vereinigten Königreich"),
    "CH": ("Switzerland", "der Schweiz"), "NO": ("Norway", "Norwegen"),
    "IS": ("Iceland", "Island"), "UA": ("Ukraine", "der Ukraine"), "RU": ("Russia", "Russland"),
    "BY": ("Belarus", "Belarus"), "RS": ("Serbia", "Serbien"), "AL": ("Albania", "Albanien"),
    "MK": ("North Macedonia", "Nordmazedonien"), "GE": ("Georgia", "Georgien"),
    "AZ": ("Azerbaijan", "Aserbaidschan"), "CN": ("China", "China"), "JP": ("Japan", "Japan"),
    "KR": ("South Korea", "Südkorea"), "IN": ("India", "Indien"), "PK": ("Pakistan", "Pakistan"),
    "BD": ("Bangladesh", "Bangladesch"), "VN": ("Vietnam", "Vietnam"),
    "TH": ("Thailand", "Thailand"), "ID": ("Indonesia", "Indonesien"),
    "MY": ("Malaysia", "Malaysia"), "TW": ("Taiwan", "Taiwan"), "IR": ("Iran", "dem Iran"),
    "IQ": ("Iraq", "dem Irak"), "SA": ("Saudi Arabia", "Saudi-Arabien"),
    "AE": ("the United Arab Emirates", "den Vereinigten Arabischen Emiraten"),
    "IL": ("Israel", "Israel"), "EG": ("Egypt", "Ägypten"), "MA": ("Morocco", "Marokko"),
    "TN": ("Tunisia", "Tunesien"), "ZA": ("South Africa", "Südafrika"),
    "US": ("the United States", "den USA"), "CA": ("Canada", "Kanada"),
    "MX": ("Mexico", "Mexiko"), "BR": ("Brazil", "Brasilien"), "AR": ("Argentina", "Argentinien"),
    "CL": ("Chile", "Chile"), "AU": ("Australia", "Australien"),
    "NZ": ("New Zealand", "Neuseeland"),
}  # fmt: skip

#: The 27 EU member states: goods moving between them pay no customs duty.
EU_MEMBERS = frozenset(
    {
        "AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR", "GR", "HR", "HU",
        "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PL", "PT", "RO", "SE", "SI", "SK",
    }
)  # fmt: skip

#: Turkish product name -> an English term the catalogue can classify. Keys are
#: lower-case stems; "elma" also matches "elmalar", "elmayı". Each value was
#: checked against the bundled catalogue (tests/test_assistant.py pins that
#: every entry classifies to something); words whose best English term still
#: landed in the wrong chapter (strawberries -> plants, chickpeas, lentils) are
#: left out rather than answered wrongly.
PRODUCTS_TR: dict[str, str] = {
    # fruit & vegetables
    "elma": "fresh apples",
    "armut": "fresh pears apples pears and quinces",
    "portakal": "fresh oranges",
    "mandalina": "mandarins",
    "limon": "fresh lemons citrus",
    "greyfurt": "grapefruit fresh or dried",
    "muz": "bananas fresh",
    "üzüm": "fresh grapes",
    "kiraz": "cherries",
    "vişne": "sour cherries",
    "kayısı": "apricots fresh",
    "şeftali": "peaches",
    "erik": "plums",
    "incir": "figs fresh or dried",
    "karpuz": "watermelons",
    "kavun": "melons",
    "nar": "pomegranates",
    "ananas": "pineapples fresh or dried",
    "avokado": "avocados fresh",
    "hurma": "dates",
    "kivi": "kiwifruit fresh",
    "domates": "tomatoes",
    "salatalık": "cucumbers",
    "patates": "potatoes",
    "soğan": "onions",
    "sarımsak": "garlic",
    "havuç": "carrots",
    "biber": "sweet peppers",
    "patlıcan": "aubergines",
    "lahana": "cabbages",
    "marul": "lettuce",
    "mantar": "mushrooms",
    "fasulye": "beans",
    "fındık": "hazelnuts",
    "ceviz": "walnuts",
    "badem": "almonds",
    "antep fıstığı": "pistachios",
    "fıstık": "pistachios",
    "kuru üzüm": "dried grapes",
    "kuru kayısı": "dried apricots",
    "zeytinyağı": "virgin olive oil",
    "zeytin": "olives",
    # food & drink
    "buğday": "wheat and meslin",
    "arpa": "barley",
    "mısır": "maize",
    "pirinç": "rice",
    "un": "wheat flour",
    "şeker": "cane or beet sugar",
    "bal": "natural honey",
    "çay": "black tea",
    "kahve": "roasted coffee",
    "kakao": "cocoa beans whole or broken raw or roasted",
    "çikolata": "chocolate",
    "bisküvi": "biscuits",
    "makarna": "pasta",
    "peynir": "cheese",
    "süt": "milk",
    "tereyağı": "butter natural",
    "yoğurt": "yogurt",
    "yumurta": "eggs",
    "et": "meat",
    "sığır eti": "meat of bovine animals",
    "tavuk": "fowls of the species gallus domesticus",
    "balık": "fish",
    "somon": "salmon",
    "karides": "shrimps",
    "ayçiçek yağı": "sunflower oil",
    "şarap": "wine of fresh grapes",
    "bira": "beer made from malt",
    "su": "mineral water",
    "meyve suyu": "orange juice",
    "salça": "tomatoes prepared or preserved",
    "baharat": "pepper of the genus piper",
    "tuz": "salt including table salt",
    # textiles & clothing
    "tişört": "t-shirt",
    "gömlek": "men's shirts of cotton",
    "pantolon": "trousers",
    "kot pantolon": "jeans",
    "kot": "jeans",
    "elbise": "dresses",
    "etek": "skirts",
    "ceket": "jackets",
    "mont": "anoraks windcheaters",
    "kazak": "jerseys pullovers",
    "çorap": "socks",
    "iç çamaşırı": "underpants",
    "ayakkabı": "footwear with uppers of leather",
    "spor ayakkabı": "sports footwear",
    "çanta": "handbags",
    "şapka": "hats",
    "eldiven": "gloves",
    "havlu": "towels",
    "halı": "carpets",
    "kumaş": "woven fabrics",
    "pamuk": "cotton not carded or combed",
    "iplik": "cotton yarn",
    "deri": "bovine leather",
    # industry & materials
    "çelik": "flat-rolled products of iron or non-alloy steel",
    "demir": "iron",
    "alüminyum": "aluminium",
    "bakır": "copper cathodes",
    "plastik": "plastics",
    "cam": "float glass",
    "kağıt": "paper and paperboard uncoated",
    "karton": "cartons boxes of corrugated paper",
    "ahşap": "wood",
    "kereste": "wood sawn lengthwise",
    "çimento": "cement",
    "mermer": "marble",
    "boya": "paints and varnishes",
    "lastik": "new pneumatic tyres",
    "cıvata": "bolts",
    "vida": "screws",
    "gübre": "fertilisers",
    "ilaç": "medicaments put up in measured doses",
    "kozmetik": "beauty or make-up preparations",
    "sabun": "soap",
    "deterjan": "washing preparations",
    "parfüm": "perfumes",
    "şampuan": "shampoos",
    # machines & electronics
    "cep telefonu": "smartphones",
    "telefon": "smartphones",
    "akıllı telefon": "smartphones",
    "bilgisayar": "laptops",
    "dizüstü bilgisayar": "laptops",
    "tablet": "portable automatic data processing machines",
    "televizyon": "television receivers",
    "monitör": "monitors",
    "kulaklık": "headphones",
    "şarj aleti": "chargers",
    "kablo": "insulated cables",
    "pil": "primary cells and batteries",
    "batarya": "lithium-ion batteries",
    "güneş paneli": "solar panel",
    "buzdolabı": "refrigerators",
    "çamaşır makinesi": "washing machines",
    "bulaşık makinesi": "dishwasher",
    "klima": "air conditioning machines comprising a motor-driven fan",
    "elektrikli süpürge": "vacuum cleaners",
    "motor": "internal combustion engines",
    "pompa": "pumps for liquids",
    "otomobil": "motor cars",
    "araba": "motor cars",
    "bisiklet": "bicycles not motorised",
    "mobilya": "wooden furniture",
    "sandalye": "chairs seats with wooden frames",
    "masa": "wooden furniture",
    "oyuncak": "other toys",
    "saat": "wrist-watches",
    "gözlük": "sunglasses",
    "prezervatif": "condom",
}

#: German product words that the German catalogue text does not use as-is.
PRODUCTS_DE: dict[str, str] = {
    "äpfel": "fresh apples",
    "apfel": "fresh apples",
    "t-shirts": "t-shirt",
    "handy": "smartphones",
}
