"""Render CustomsIQ results in SAP GTS terminology and data shapes.

⚠️ **This is a terminology and data-shape simulation, not an SAP integration.**
CustomsIQ is not connected to any SAP system and never has been. This module
reshapes CustomsIQ's own results into structures whose field names and
vocabulary mirror SAP GTS — the documented `BAPIRET2` return structure and GTS's
own functional-area and document-status terminology — so that the domain
concepts are recognisable at a glance. The output is **not** a valid IDoc or BAPI
payload and no real SAP system would accept it. Real integration would require
licensed SAP GTS plus an SAP BTP ABAP Environment (or an on-premise SAP system
reachable over RFC/OData), none of which this project has, uses, or claims.

What is real here: the `BAPIRET2` field names, types and lengths, and the GTS
functional-area names. What is CustomsIQ's own construction: the message class,
the message numbers, the header envelope and the document-status vocabulary.
Every payload carries `SIMULATION: true` and a disclaimer string so that it stays
self-labelling even when copied out of context.

Read-only by construction: every function here takes an already-computed result
object and returns a rendered structure. Nothing in this module opens a database
connection or calls a decision function — a test asserts both.
"""

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

from src.customsiq.models import ReviewDecision
from src.customsiq.risk import RiskAssessment, RiskFactor
from src.customsiq.tariff_calculator import PREFERENTIAL, STANDARD

#: GTS is organised into three functional areas. SPL screening, embargo checks
#: and Legal Control sit in Compliance Management; declarations, classification
#: and duty determination in Customs Management; Preference Processing (and
#: letters of credit, restitution) in Risk Management.
AREA_COMPLIANCE = "COMPLIANCE_MGMT"
AREA_CUSTOMS = "CUSTOMS_MGMT"
AREA_RISK = "RISK_MGMT"

SERVICE_SPL = "SPL_SCREENING"
SERVICE_CLASSIFICATION = "CLASSIFICATION"
SERVICE_PREFERENCE_DUTY = "PREFERENCE_DUTY"
SERVICE_RISK = "RISK_ASSESSMENT"
SERVICE_LEGAL_CONTROL = "LEGAL_CONTROL"

#: Message class. The `Z` prefix is SAP's customer namespace — the conventional
#: way of saying "this is not a standard SAP object", which is exactly the claim
#: being made here.
MESSAGE_CLASS = "ZCUSTOMSIQ_GTS"

#: BAPIRET2-SYSTEM is a *logical system* name, not a real SAP system ID.
SOURCE_SYSTEM = "CUSTOMSIQ"

#: Travels inside every payload, so the output stays labelled if it is copied
#: somewhere this module's docstring isn't.
DISCLAIMER = (
    "Terminology simulation generated by CustomsIQ. Not an SAP system export "
    "and not a valid BAPI or IDoc payload."
)

#: The real field lengths of the BAPIRET2 structure. Values are truncated to
#: these rather than emitted at arbitrary width: honouring the constraints is
#: part of demonstrating that the structure is understood.
FIELD_LENGTHS = {
    "TYPE": 1,
    "ID": 20,
    "NUMBER": 3,
    "MESSAGE": 220,
    "LOG_NO": 20,
    "LOG_MSG_NO": 6,
    "MESSAGE_V1": 50,
    "MESSAGE_V2": 50,
    "MESSAGE_V3": 50,
    "MESSAGE_V4": 50,
    "PARAMETER": 32,
    "FIELD": 30,
    "SYSTEM": 10,
}

# GTS blocks a document when a check fails, and the block lifts only when
# somebody releases it. These four values mirror that vocabulary.
STATUS_BLOCKED = "BLOCKED"
STATUS_PENDING = "PENDING"
STATUS_RELEASED = "RELEASED"
STATUS_NOT_BLOCKED = "NOT_BLOCKED"

# Message numbers, stable per outcome (BAPIRET2-NUMBER is NUMC(3)).
MSG_SPL_HIT = "001"
MSG_SPL_NEAR_MISS = "002"
MSG_SPL_CLEAN = "003"
MSG_CLASS_DETERMINED = "010"
MSG_CLASS_FAILED = "011"
MSG_CLASS_SUPPLIED = "012"
MSG_DUTY_PREFERENTIAL = "020"
MSG_DUTY_STANDARD = "021"
MSG_DUTY_NO_RATE = "022"
MSG_RISK_HIGH = "030"
MSG_RISK_MEDIUM = "031"
MSG_RISK_LOW = "032"
MSG_REVIEW_RELEASED = "040"
MSG_REVIEW_BLOCKED = "041"
MSG_REVIEW_PENDING = "042"
MSG_REVIEW_NONE = "043"

# Score bands used to turn a RiskFactor back into an outcome. These mirror the
# constants documented in risk.py (screening hit 1.0, near miss 0.4, clean 0.0;
# classification 0.0 when a code was given, 1.0 when nothing matched) without
# importing that module's private names. The pinned worked examples in
# tests/test_sap_gts_bridge.py fail if the two ever drift apart.
_BAND_HIT = 0.9
_BAND_PRESENT = 0.2
_BAND_DUTY_MISSING = 0.55


def _fit(value: object, field: str) -> str:
    """Render a value as text, truncated to its real BAPIRET2 field length."""
    return str(value)[: FIELD_LENGTHS[field]]


@dataclass(frozen=True)
class GtsMessage:
    """One row of a BAPIRET2-shaped RETURN table.

    Attributes:
        type: "S" success | "E" error | "W" warning | "I" info | "A" abort.
        number: Message number, three digits.
        message: The rendered message text.
        parameter: Which GTS service produced it, e.g. "SPL_SCREENING".
        field: The CustomsIQ factor behind it, so a reader can trace it back.
        area: The GTS functional area the service belongs to.
        variables: Values SAP would substitute into the message (V1..V4).
    """

    type: str
    number: str
    message: str
    parameter: str
    field: str
    area: str
    variables: tuple = ()

    def as_return_row(self, row: int, log_no: str) -> dict:
        """Render as a BAPIRET2 row, with SAP's field names and lengths.

        Args:
            row: Position in the RETURN table (BAPIRET2-ROW is an integer).
            log_no: The CustomsIQ subject reference, used as the log number.

        Returns:
            A dict keyed by the real BAPIRET2 field names.
        """
        padded = (list(self.variables) + ["", "", "", ""])[:4]
        return {
            "TYPE": _fit(self.type, "TYPE"),
            "ID": _fit(MESSAGE_CLASS, "ID"),
            "NUMBER": _fit(self.number, "NUMBER"),
            "MESSAGE": _fit(self.message, "MESSAGE"),
            "LOG_NO": _fit(log_no, "LOG_NO"),
            "LOG_MSG_NO": _fit(f"{row:06d}", "LOG_MSG_NO"),
            "MESSAGE_V1": _fit(padded[0], "MESSAGE_V1"),
            "MESSAGE_V2": _fit(padded[1], "MESSAGE_V2"),
            "MESSAGE_V3": _fit(padded[2], "MESSAGE_V3"),
            "MESSAGE_V4": _fit(padded[3], "MESSAGE_V4"),
            "PARAMETER": _fit(self.parameter, "PARAMETER"),
            "ROW": row,
            "FIELD": _fit(self.field, "FIELD"),
            "SYSTEM": _fit(SOURCE_SYSTEM, "SYSTEM"),
        }


@dataclass(frozen=True)
class GtsDocument:
    """A rendered check document: a GTS-style header plus a RETURN table.

    Attributes:
        document_type: "COMPLIANCE_CHECK" or "LEGAL_CONTROL_LOG".
        status: BLOCKED | PENDING | RELEASED | NOT_BLOCKED.
        subject_reference: The CustomsIQ reference this document describes.
        messages: The RETURN table, in order.
        generated_at: ISO 8601 timestamp.
    """

    document_type: str
    status: str
    subject_reference: str
    messages: list
    generated_at: str

    @property
    def functional_areas(self) -> list:
        """The GTS areas this document's messages span, in a stable order."""
        order = (AREA_COMPLIANCE, AREA_CUSTOMS, AREA_RISK)
        present = {message.area for message in self.messages}
        return [area for area in order if area in present]

    def as_payload(self) -> dict:
        """Render the whole document, header included.

        The header carries `SIMULATION` and `DISCLAIMER` deliberately: the
        payload has to stay self-labelling if it is pasted somewhere else.
        """
        return {
            "HEADER": {
                "DOCUMENT_TYPE": self.document_type,
                "FUNCTIONAL_AREAS": self.functional_areas,
                "DOCUMENT_STATUS": self.status,
                "SUBJECT_REFERENCE": self.subject_reference,
                "SOURCE_SYSTEM": SOURCE_SYSTEM,
                "GENERATED_AT": self.generated_at,
                "SIMULATION": True,
                "DISCLAIMER": DISCLAIMER,
            },
            "RETURN": [
                message.as_return_row(row, self.subject_reference)
                for row, message in enumerate(self.messages, start=1)
            ],
        }


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def render_screening(factor: RiskFactor, party_name: str) -> GtsMessage:
    """Render the screening factor as an SPL Screening message.

    A hit is an error because that is what blocks a document in GTS; a
    below-threshold near miss is a warning; a clean screen is a success.
    """
    if factor.score >= _BAND_HIT:
        return GtsMessage(
            type="E",
            number=MSG_SPL_HIT,
            message=f"Sanctioned party list hit for '{party_name}' — {factor.explanation}",
            parameter=SERVICE_SPL,
            field="screening",
            area=AREA_COMPLIANCE,
            variables=(party_name, f"{factor.score:.2f}"),
        )
    if factor.score >= _BAND_PRESENT:
        return GtsMessage(
            type="W",
            number=MSG_SPL_NEAR_MISS,
            message=f"Sanctioned party list near miss for '{party_name}' — {factor.explanation}",
            parameter=SERVICE_SPL,
            field="screening",
            area=AREA_COMPLIANCE,
            variables=(party_name, f"{factor.score:.2f}"),
        )
    return GtsMessage(
        type="S",
        number=MSG_SPL_CLEAN,
        message=f"No sanctioned party list hit for '{party_name}'.",
        parameter=SERVICE_SPL,
        field="screening",
        area=AREA_COMPLIANCE,
        variables=(party_name, f"{factor.score:.2f}"),
    )


def render_classification(factor: RiskFactor, hs_code: Optional[str]) -> GtsMessage:
    """Render the classification factor as a Classification message.

    GTS calls this determining a commodity code for a product. A code supplied
    by the caller is information, not a determination; failing to find one is a
    warning, because the downstream duty determination has nothing to work with.
    """
    if factor.score >= _BAND_HIT:
        return GtsMessage(
            type="W",
            number=MSG_CLASS_FAILED,
            message=f"No commodity code could be determined — {factor.explanation}",
            parameter=SERVICE_CLASSIFICATION,
            field="classification",
            area=AREA_CUSTOMS,
            variables=("", f"{factor.score:.2f}"),
        )
    code = hs_code or ""
    if factor.score <= 0.0:
        return GtsMessage(
            type="I",
            number=MSG_CLASS_SUPPLIED,
            message=f"Commodity code {code} supplied; no determination required.",
            parameter=SERVICE_CLASSIFICATION,
            field="classification",
            area=AREA_CUSTOMS,
            variables=(code, f"{factor.score:.2f}"),
        )
    return GtsMessage(
        type="I",
        number=MSG_CLASS_DETERMINED,
        message=f"Commodity code {code} determined — {factor.explanation}",
        parameter=SERVICE_CLASSIFICATION,
        field="classification",
        area=AREA_CUSTOMS,
        variables=(code, f"{factor.score:.2f}"),
    )


def render_duty(factor: RiskFactor) -> GtsMessage:
    """Render the duty factor as a duty-determination / preference message.

    Duty determination is Customs Management; a preferential rate is the
    *result* of what GTS calls Preference Processing, which lives in Risk
    Management — so a preferential outcome is tagged to that area.
    """
    explanation = factor.explanation
    # Branch on the factor's structured discriminator, not on its English
    # prose: the sentence is now localizable, and sniffing it here would
    # route every duty message to the no-rate warning the moment it changed.
    rate_type = factor.explanation_params.get("rate_type")
    if rate_type == PREFERENTIAL:
        return GtsMessage(
            type="S",
            number=MSG_DUTY_PREFERENTIAL,
            message=f"Preferential duty rate applied — {explanation}",
            parameter=SERVICE_PREFERENCE_DUTY,
            field="duty",
            area=AREA_RISK,
            variables=(explanation, f"{factor.score:.2f}"),
        )
    if rate_type == STANDARD:
        return GtsMessage(
            type="I",
            number=MSG_DUTY_STANDARD,
            message=f"Standard (MFN) duty rate applied — {explanation}",
            parameter=SERVICE_PREFERENCE_DUTY,
            field="duty",
            area=AREA_CUSTOMS,
            variables=(explanation, f"{factor.score:.2f}"),
        )
    return GtsMessage(
        type="W",
        number=MSG_DUTY_NO_RATE,
        message=f"Duty could not be determined — {explanation}",
        parameter=SERVICE_PREFERENCE_DUTY,
        field="duty",
        area=AREA_CUSTOMS,
        variables=(explanation, f"{factor.score:.2f}"),
    )


def _render_overall(assessment: RiskAssessment) -> GtsMessage:
    """Render the composite outcome, which is what decides the document status."""
    level = assessment.level
    score = f"{assessment.composite_score:.4f}"
    if level == "high":
        return GtsMessage(
            type="E",
            number=MSG_RISK_HIGH,
            message=f"Composite risk HIGH ({score}) — document blocked pending review.",
            parameter=SERVICE_RISK,
            field="composite_score",
            area=AREA_RISK,
            variables=(level.upper(), score),
        )
    if level == "medium":
        return GtsMessage(
            type="W",
            number=MSG_RISK_MEDIUM,
            message=f"Composite risk MEDIUM ({score}) — manual check recommended.",
            parameter=SERVICE_RISK,
            field="composite_score",
            area=AREA_RISK,
            variables=(level.upper(), score),
        )
    return GtsMessage(
        type="S",
        number=MSG_RISK_LOW,
        message=f"Composite risk LOW ({score}) — no block raised.",
        parameter=SERVICE_RISK,
        field="composite_score",
        area=AREA_RISK,
        variables=(level.upper(), score),
    )


_STATUS_FOR_LEVEL = {
    "high": STATUS_BLOCKED,
    "medium": STATUS_PENDING,
    "low": STATUS_NOT_BLOCKED,
}


def compliance_check(
    assessment: RiskAssessment, party_name: str, subject_reference: str
) -> GtsDocument:
    """Render a composite risk assessment as a GTS-style check document.

    Args:
        assessment: An existing `risk.assess_shipment` result. This function
            performs no scoring of its own — every number below comes from it.
        party_name: The screened party, for the SPL message variables.
        subject_reference: CustomsIQ's deterministic reference for the subject.

    Returns:
        A GtsDocument spanning whichever GTS areas the factors touched.
    """
    by_name = {factor.name: factor for factor in assessment.factors}
    messages = []
    if "screening" in by_name:
        messages.append(render_screening(by_name["screening"], party_name))
    if "classification" in by_name:
        messages.append(render_classification(by_name["classification"], assessment.hs_code))
    if "duty" in by_name:
        messages.append(render_duty(by_name["duty"]))
    messages.append(_render_overall(assessment))

    return GtsDocument(
        document_type="COMPLIANCE_CHECK",
        status=_STATUS_FOR_LEVEL.get(assessment.level, STATUS_PENDING),
        subject_reference=subject_reference,
        messages=messages,
        generated_at=_now(),
    )


_STATUS_FOR_DECISION = {
    "approved": STATUS_RELEASED,
    "rejected": STATUS_BLOCKED,
    "flagged": STATUS_PENDING,
}

_MESSAGE_FOR_DECISION = {
    "approved": ("S", MSG_REVIEW_RELEASED, "released by"),
    "rejected": ("E", MSG_REVIEW_BLOCKED, "blocked by"),
    "flagged": ("W", MSG_REVIEW_PENDING, "flagged for further checking by"),
}


def legal_control_log(decisions: list, subject_reference: str) -> GtsDocument:
    """Render recorded review decisions as a block/release check log.

    This is the closest analogue CustomsIQ has to how GTS handles a failed
    compliance check: the document is blocked, and stays blocked until somebody
    with the authority releases it, with every step kept in a log. It is *not*
    Legal Control in GTS's narrow sense — that is export-licence determination
    for dual-use goods, and CustomsIQ has no licence master to do it with.

    Args:
        decisions: Existing `ReviewDecision` records, most recent first.
        subject_reference: The reference they were recorded against.

    Returns:
        A GtsDocument whose status reflects the most recent decision.
    """
    if not decisions:
        return GtsDocument(
            document_type="LEGAL_CONTROL_LOG",
            status=STATUS_NOT_BLOCKED,
            subject_reference=subject_reference,
            messages=[
                GtsMessage(
                    type="I",
                    number=MSG_REVIEW_NONE,
                    message="No review decision recorded for this subject.",
                    parameter=SERVICE_LEGAL_CONTROL,
                    field="review_decisions",
                    area=AREA_COMPLIANCE,
                )
            ],
            generated_at=_now(),
        )

    messages = []
    for decision in decisions:
        message_type, number, phrase = _MESSAGE_FOR_DECISION[decision.decision]
        messages.append(
            GtsMessage(
                type=message_type,
                number=number,
                message=(
                    f"{decision.subject_type.capitalize()} check {phrase} "
                    f"{decision.reviewer_name} at {decision.reviewed_at}."
                ),
                parameter=SERVICE_LEGAL_CONTROL,
                field=decision.subject_type,
                area=AREA_COMPLIANCE,
                variables=(
                    decision.reviewer_name,
                    decision.reviewed_at,
                    decision.subject_type,
                    decision.comment or "",
                ),
            )
        )

    latest: ReviewDecision = decisions[0]
    return GtsDocument(
        document_type="LEGAL_CONTROL_LOG",
        status=_STATUS_FOR_DECISION.get(latest.decision, STATUS_PENDING),
        subject_reference=subject_reference,
        messages=messages,
        generated_at=_now(),
    )
